[package]
name = "netperf"
version = "0.2.1"
description = "A network performance measurement tool"
authors = ["Ahmed Soliman <me@ahmedsoliman.com>"]
edition = "2018"
repository = "https://github.com/AhmedSoliman/netperf"
license = "MIT OR Apache-2.0"
keywords = ["network", "performance", "iperf3"]
categories = ["command-line-utilities", "simulation"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0"
colored = "2.0"
env_logger = "0.8"
log = "0.4"
nix = "0.20"
structopt = "0.3"
bytes = "1.0"
clap-verbosity-flag = "0.3"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.2.0", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "time",
    "sync",
    "macros",
    "fs",
    "io-util"
] }
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
pretty_assertions = "0.6"
tokio = { version = "1.2.0", features = ["test-util"] }
tokio-stream = { version = "0.1" }
